---
- name: Installing bat
  package:
    name: bat
    state: present
  become: yes

- name: Installing fzf
  package:
    name: fzf
    state: present
  become: yes

- name: Installing jq
  package:
    name: jq
    state: present
  become: yes
